version: "2"
services:
  web:
    build: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"
    environment:
      - VIRTUAL_PORT=3000
      - VIRTUAL_HOST=box.olegsas.by,www.box.olegsas.by
    links: 
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro      
